server.port=8211

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://michaelxsd_db_user:MNOH51Ttk3nYAzpw@cluster01.ffhi9v8.mongodb.net/gamehub_db
spring.data.mongodb.database=gamehub_db

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver=INFO

# JWT
jwt.secret=gamehub_super_secreto_2026_clave_larga_minimo_256bits_segura
jwt.expiration=86400000